# This file was generated by GoReleaser. DO NOT EDIT.
cask "writrun" do
  version "0.0.2"

  on_macos do
    on_arm do
      sha256 "bd84703b330820ea3db5ff68b43227a29ab8863988fbf1a4fcf4572f426b3b35"
      url "https://github.com/thomasfranke/writrun-cli/releases/download/v#{version}/writrun_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f5fa911b6e1b5f12ed0cdfc6fa25c2f6f46de0967d12c294b83b5551a0a7b6a6"
      url "https://github.com/thomasfranke/writrun-cli/releases/download/v#{version}/writrun_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e2922438b212d73854ad36c6134eaf1afa459b841733e3ada2f44bf80be24515"
      url "https://github.com/thomasfranke/writrun-cli/releases/download/v#{version}/writrun_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "12f7aee8e447e2ad91f2d2f9e636d05b53ad499208cb39792e356e7ff13f8f00"
      url "https://github.com/thomasfranke/writrun-cli/releases/download/v#{version}/writrun_#{version}_linux_amd64.tar.gz"
    end
  end

  name "writrun"
  desc "The porcelain for WritRun, one binary over the methodology's own scripts."
  homepage "https://github.com/thomasfranke/writrun-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "writrun"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/writrun"]
    end
  end

  # No zap stanza required
end
