# This file was generated by GoReleaser. DO NOT EDIT.
cask "writrun" do
  version "0.0.1"

  on_macos do
    on_arm do
      sha256 "fb3ff242c73d73dbff6e9442ee5ff7b0aefbd84e47b7e39417878c915c32b20b"
      url "https://github.com/thomasfranke/writrun-cli/releases/download/v#{version}/writrun_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "51f35d66f41ede9be9d1b6b91260a85e10400e7a3b4e9220793fef7dbda2736e"
      url "https://github.com/thomasfranke/writrun-cli/releases/download/v#{version}/writrun_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "16d36143294c9e55c39d48591f7c07fd7f4990a2258225d01ff2511971413000"
      url "https://github.com/thomasfranke/writrun-cli/releases/download/v#{version}/writrun_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "485faafce1b3cb537d2f6adb3d54c2e276a80766c4a35f699237e6c36d773de4"
      url "https://github.com/thomasfranke/writrun-cli/releases/download/v#{version}/writrun_#{version}_linux_amd64.tar.gz"
    end
  end

  name "writrun"
  desc "The porcelain for WritRun, one binary over the methodology's own scripts."
  homepage "https://github.com/thomasfranke/writrun-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "writrun"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/writrun"]
    end
  end

  # No zap stanza required
end
